"""renomear_atletacontrato_atletacontratoclube

Revision ID: 07b6f2cf3cf8
Revises: 4c3fca061008
Create Date: 2024-05-16 07:22:53.337821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b6f2cf3cf8'
down_revision: Union[str, None] = '4c3fca061008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atletacontratoclube',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atletacontratoclube_atleta_id'), 'atletacontratoclube', ['atleta_id'], unique=False)
    op.create_index(op.f('ix_atletacontratoclube_contrato_id'), 'atletacontratoclube', ['contrato_id'], unique=False)
    op.drop_index('ix_atletacontrato_atleta_id', table_name='atletacontrato')
    op.drop_index('ix_atletacontrato_contrato_id', table_name='atletacontrato')
    op.drop_table('atletacontrato')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atletacontrato',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('data_atualizado', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contrato_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], name='FK__atletacon__atlet__756D6ECB'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], name='FK__atletacon__contr__76619304'),
    sa.PrimaryKeyConstraint('atleta_id', 'contrato_id', name='PK__atletaco__B703D67E6E43CD4B')
    )
    op.create_index('ix_atletacontrato_contrato_id', 'atletacontrato', ['contrato_id'], unique=False)
    op.create_index('ix_atletacontrato_atleta_id', 'atletacontrato', ['atleta_id'], unique=False)
    op.drop_index(op.f('ix_atletacontratoclube_contrato_id'), table_name='atletacontratoclube')
    op.drop_index(op.f('ix_atletacontratoclube_atleta_id'), table_name='atletacontratoclube')
    op.drop_table('atletacontratoclube')
    # ### end Alembic commands ###
