"""remover_campos_obrigatorios_posicao

Revision ID: 127b0a16a9a2
Revises: 1a48e365991b
Create Date: 2024-05-05 19:25:18.847483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127b0a16a9a2'
down_revision: Union[str, None] = '1a48e365991b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
