"""remover_tabela_atletaposicao

Revision ID: 1a48e365991b
Revises: 4d9806d899de
Create Date: 2024-05-05 19:20:24.321407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a48e365991b'
down_revision: Union[str, None] = '4d9806d899de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atletaposicao')
    op.drop_table('systranschemas')
    op.drop_table('atletacaracteristica')
    op.add_column('posicao', sa.Column('primeira', sa.Enum('atacante', 'goleiro', 'lateral', 'meia', 'volante', 'zagueiro', name='posicaotypes'), nullable=True))
    op.add_column('posicao', sa.Column('segunda', sa.Enum('atacante', 'goleiro', 'lateral', 'meia', 'volante', 'zagueiro', name='posicaotypes'), nullable=True))
    op.add_column('posicao', sa.Column('terceira', sa.Enum('atacante', 'goleiro', 'lateral', 'meia', 'volante', 'zagueiro', name='posicaotypes'), nullable=True))
    op.add_column('posicao', sa.Column('atleta_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posicao', 'atleta', ['atleta_id'], ['id'])
    op.drop_column('posicao', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posicao', sa.Column('nome', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posicao', type_='foreignkey')
    op.drop_column('posicao', 'atleta_id')
    op.drop_column('posicao', 'terceira')
    op.drop_column('posicao', 'segunda')
    op.drop_column('posicao', 'primeira')
    op.create_table('atletacaracteristica',
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('caracteristica_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], name='FK__atletacar__atlet__412EB0B6'),
    sa.ForeignKeyConstraint(['caracteristica_id'], ['posicao.id'], name='FK__atletacar__carac__4222D4EF'),
    sa.PrimaryKeyConstraint('atleta_id', 'caracteristica_id', name='PK__atletaca__668C0CA114E38C80')
    )
    op.create_table('systranschemas',
    sa.Column('tabid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('startlsn', sa.BINARY(length=10), autoincrement=False, nullable=False),
    sa.Column('endlsn', sa.BINARY(length=10), autoincrement=False, nullable=False),
    sa.Column('typeid', sa.INTEGER(), server_default=sa.text('((52))'), autoincrement=False, nullable=False)
    )
    op.create_table('atletaposicao',
    sa.Column('data_criacao', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('posicao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], name='FK__atletapos__atlet__48CFD27E')
    )
    # ### end Alembic commands ###
