"""tabela_usuario

Revision ID: 2f8323ed056c
Revises: 127b0a16a9a2
Create Date: 2024-05-06 22:42:16.655177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f8323ed056c'
down_revision: Union[str, None] = '127b0a16a9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuariotipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('admin', 'treinador', 'externo', name='usuariotipotypes'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('usuario_tipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_tipo_id'], ['usuariotipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('usuariotipo')
    # ### end Alembic commands ###
