"""revisao_modelagem

Revision ID: 305e0ac5b526
Revises: b509b0b19669
Create Date: 2024-04-30 23:39:25.975398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '305e0ac5b526'
down_revision: Union[str, None] = 'b509b0b19669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atletacaracteristica',
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('caracteristica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.ForeignKeyConstraint(['caracteristica_id'], ['posicao.id'], ),
    sa.PrimaryKeyConstraint('atleta_id', 'caracteristica_id')
    )
    op.create_table('caracteristica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicoobservacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Enum('desempenho', 'relacionamento', name='obsevacaotypes'), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('atletaposicao', sa.Column('data_criacao', sa.DateTime(), nullable=False))
    op.add_column('atletaposicao', sa.Column('posicao_primaria_id', sa.Integer(), nullable=False))
    op.add_column('atletaposicao', sa.Column('posicao_secundaria_id', sa.Integer(), nullable=False))
    op.add_column('atletaposicao', sa.Column('posicao_terciaria_id', sa.Integer(), nullable=False))
    op.drop_constraint('FK__atletapos__posic__49C3F6B7', 'atletaposicao', type_='foreignkey')
    op.create_foreign_key(None, 'atletaposicao', 'posicao', ['posicao_secundaria_id'], ['id'])
    op.create_foreign_key(None, 'atletaposicao', 'posicao', ['posicao_terciaria_id'], ['id'])
    op.create_foreign_key(None, 'atletaposicao', 'posicao', ['posicao_primaria_id'], ['id'])
    op.drop_column('atletaposicao', 'posicao_id')
    op.add_column('clube', sa.Column('data_inicio', sa.Date(), nullable=False))
    op.add_column('clube', sa.Column('data_fim', sa.Date(), nullable=True))
    op.drop_column('clube', 'ativo')
    op.add_column('historicocompeticao', sa.Column('gols', sa.Integer(), nullable=False))
    op.add_column('historicomaterial', sa.Column('preco', sa.Float(), nullable=False))
    op.add_column('relacionamento', sa.Column('data_avaliacao', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relacionamento', 'data_avaliacao')
    op.drop_column('historicomaterial', 'preco')
    op.drop_column('historicocompeticao', 'gols')
    op.add_column('clube', sa.Column('ativo', mssql.BIT(), autoincrement=False, nullable=False))
    op.drop_column('clube', 'data_fim')
    op.drop_column('clube', 'data_inicio')
    op.add_column('atletaposicao', sa.Column('posicao_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletaposicao', type_='foreignkey')
    op.drop_constraint(None, 'atletaposicao', type_='foreignkey')
    op.drop_constraint(None, 'atletaposicao', type_='foreignkey')
    op.create_foreign_key('FK__atletapos__posic__49C3F6B7', 'atletaposicao', 'posicao', ['posicao_id'], ['id'])
    op.drop_column('atletaposicao', 'posicao_terciaria_id')
    op.drop_column('atletaposicao', 'posicao_secundaria_id')
    op.drop_column('atletaposicao', 'posicao_primaria_id')
    op.drop_column('atletaposicao', 'data_criacao')
    op.drop_table('historicoobservacao')
    op.drop_table('caracteristica')
    op.drop_table('atletacaracteristica')
    op.drop_table('perfil')
    # ### end Alembic commands ###
