"""fix_adicionar_constraint_email

Revision ID: 3d606348aa07
Revises: ff4de6c59f4e
Create Date: 2024-05-06 23:04:19.775890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d606348aa07'
down_revision: Union[str, None] = 'ff4de6c59f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
