"""fix_atletacontrato

Revision ID: 4c3fca061008
Revises: e39a34050fb3
Create Date: 2024-05-16 00:16:13.378157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3fca061008'
down_revision: Union[str, None] = 'e39a34050fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletacontrato', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_atletacontrato_atleta_id'), 'atletacontrato', ['atleta_id'], unique=False)
    op.create_index(op.f('ix_atletacontrato_contrato_id'), 'atletacontrato', ['contrato_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atletacontrato_contrato_id'), table_name='atletacontrato')
    op.drop_index(op.f('ix_atletacontrato_atleta_id'), table_name='atletacontrato')
    op.drop_column('atletacontrato', 'id')
    # ### end Alembic commands ###
