"""refix_adicionar_constraint_email

Revision ID: 4c7bcd5a7975
Revises: 3d606348aa07
Create Date: 2024-05-06 23:09:08.099091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7bcd5a7975'
down_revision: Union[str, None] = '3d606348aa07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
