"""criar_tabela_atleta_imagens

Revision ID: 573cc15482f9
Revises: d670edc27794
Create Date: 2024-05-27 17:47:18.036259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '573cc15482f9'
down_revision: Union[str, None] = 'd670edc27794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atletaavatar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atletaimagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usuarioavatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarioavatar',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('blob_url', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('data_atualizado', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], name='FK__usuarioav__atlet__57DD0BE4'),
    sa.PrimaryKeyConstraint('id', name='PK__usuarioa__3213E83FFB14DB65')
    )
    op.drop_table('atletaimagens')
    op.drop_table('atletaavatar')
    # ### end Alembic commands ###
