"""renomear_tabela_controle_para_historicocontrole

Revision ID: 5f04000bc6ba
Revises: b7d17cec01b9
Create Date: 2024-05-01 10:28:46.476622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5f04000bc6ba'
down_revision: Union[str, None] = 'b7d17cec01b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicocontrole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('data_controle', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('historicomaterial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicomaterial',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('data_atualizado', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preco', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], name='FK__historico__atlet__656C112C'),
    sa.PrimaryKeyConstraint('id', name='PK__historic__3213E83FF63A4E0B')
    )
    op.drop_table('historicocontrole')
    # ### end Alembic commands ###
