"""criar_campo_assistencias_em_competicoes

Revision ID: 62005f05f71e
Revises: 631b67bde145
Create Date: 2024-05-13 18:58:32.550360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62005f05f71e'
down_revision: Union[str, None] = '631b67bde145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicocompeticao', sa.Column('assistencias', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historicocompeticao', 'assistencias')
    # ### end Alembic commands ###
