"""adicionar_data_avaliacao_caracteristicas

Revision ID: 78fd4d0a0235
Revises: 6c499bdec772
Create Date: 2024-05-10 23:17:31.292466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fd4d0a0235'
down_revision: Union[str, None] = '6c499bdec772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caracteristicaatacante', sa.Column('data_avaliacao', sa.Date(), nullable=True))
    op.add_column('caracteristicafisica', sa.Column('data_avaliacao', sa.Date(), nullable=True))
    op.add_column('caracteristicagoleiro', sa.Column('data_avaliacao', sa.Date(), nullable=True))
    op.add_column('caracteristicalateral', sa.Column('data_avaliacao', sa.Date(), nullable=True))
    op.add_column('caracteristicameia', sa.Column('data_avaliacao', sa.Date(), nullable=True))
    op.add_column('caracteristicavolante', sa.Column('data_avaliacao', sa.Date(), nullable=True))
    op.add_column('caracteristicazagueiro', sa.Column('data_avaliacao', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caracteristicazagueiro', 'data_avaliacao')
    op.drop_column('caracteristicavolante', 'data_avaliacao')
    op.drop_column('caracteristicameia', 'data_avaliacao')
    op.drop_column('caracteristicalateral', 'data_avaliacao')
    op.drop_column('caracteristicagoleiro', 'data_avaliacao')
    op.drop_column('caracteristicafisica', 'data_avaliacao')
    op.drop_column('caracteristicaatacante', 'data_avaliacao')
    # ### end Alembic commands ###
