"""alterar_nome_tabela_clube_para_historicoclube

Revision ID: 79c527405344
Revises: 305e0ac5b526
Create Date: 2024-05-01 00:01:43.178012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79c527405344'
down_revision: Union[str, None] = '305e0ac5b526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicoclube',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clube')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clube',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('data_atualizado', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], name='FK__clube__atleta_id__6E01572D'),
    sa.PrimaryKeyConstraint('id', name='PK__clube__3213E83F15DBE584')
    )
    op.drop_table('historicoclube')
    # ### end Alembic commands ###
