"""rerefix_adicionar_constraint_email

Revision ID: 8b486b216e44
Revises: 4c7bcd5a7975
Create Date: 2024-05-06 23:13:15.847692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b486b216e44'
down_revision: Union[str, None] = '4c7bcd5a7975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
