"""create_tabela_relacionamento

Revision ID: 8fd301618910
Revises: db00c5363f7e
Create Date: 2024-04-23 19:39:15.189306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd301618910'
down_revision: Union[str, None] = 'db00c5363f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relacionamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receptividade_contrato', sa.Integer(), nullable=False),
    sa.Column('satisfacao_empresa', sa.Integer(), nullable=False),
    sa.Column('satisfacao_clube', sa.Integer(), nullable=False),
    sa.Column('relacao_familiares', sa.Integer(), nullable=False),
    sa.Column('influencias_externas', sa.Integer(), nullable=False),
    sa.Column('pendencia_empresa', sa.Boolean(), nullable=False),
    sa.Column('pendencia_clube', sa.Boolean(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relacionamento')
    # ### end Alembic commands ###
