"""Initial

Revision ID: a2226cd86e5e
Revises: 
Create Date: 2024-05-01 16:08:22.826475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2226cd86e5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atletacaracteristica',
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('caracteristica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.ForeignKeyConstraint(['caracteristica_id'], ['posicao.id'], ),
    sa.PrimaryKeyConstraint('atleta_id', 'caracteristica_id')
    )
    op.create_table('atletacontrato',
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('atleta_id', 'contrato_id')
    )
    op.create_table('atletaposicao',
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('posicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.ForeignKeyConstraint(['posicao_id'], ['posicao.id'], ),
    sa.PrimaryKeyConstraint('posicao_id')
    )
    op.create_table('caracteristica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicoclube',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicocompeticao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_competicao', sa.Date(), nullable=False),
    sa.Column('jogos_completos', sa.Integer(), nullable=False),
    sa.Column('jogos_parciais', sa.Integer(), nullable=False),
    sa.Column('minutagem', sa.Integer(), nullable=False),
    sa.Column('gols', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicocontrole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('data_controle', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicolesao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_lesao', sa.Date(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicoobservacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Enum('desempenho', 'relacionamento', name='obsevacaotypes'), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relacionamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receptividade_contrato', sa.Integer(), nullable=False),
    sa.Column('satisfacao_empresa', sa.Integer(), nullable=False),
    sa.Column('satisfacao_clube', sa.Integer(), nullable=False),
    sa.Column('relacao_familiares', sa.Integer(), nullable=False),
    sa.Column('influencias_externas', sa.Integer(), nullable=False),
    sa.Column('pendencia_empresa', sa.Boolean(), nullable=False),
    sa.Column('pendencia_clube', sa.Boolean(), nullable=False),
    sa.Column('data_avaliacao', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relacionamento')
    op.drop_table('historicoobservacao')
    op.drop_table('historicolesao')
    op.drop_table('historicocontrole')
    op.drop_table('historicocompeticao')
    op.drop_table('historicoclube')
    op.drop_table('caracteristica')
    op.drop_table('atletaposicao')
    op.drop_table('atletacontrato')
    op.drop_table('atletacaracteristica')
    op.drop_table('posicao')
    op.drop_table('perfil')
    op.drop_table('contrato')
    op.drop_table('atleta')
    # ### end Alembic commands ###
