"""remover_multiplas_FK_tabela_historiclube

Revision ID: b7d17cec01b9
Revises: 79c527405344
Create Date: 2024-05-01 00:50:39.435612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d17cec01b9'
down_revision: Union[str, None] = '79c527405344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletaposicao', sa.Column('posicao_id', sa.Integer(), nullable=False))
    op.drop_constraint('FK__atletapos__posic__531856C7', 'atletaposicao', type_='foreignkey')
    op.drop_constraint('FK__atletapos__posic__5224328E', 'atletaposicao', type_='foreignkey')
    op.drop_constraint('FK__atletapos__posic__51300E55', 'atletaposicao', type_='foreignkey')
    op.create_foreign_key(None, 'atletaposicao', 'posicao', ['posicao_id'], ['id'])
    op.drop_column('atletaposicao', 'posicao_primaria_id')
    op.drop_column('atletaposicao', 'posicao_secundaria_id')
    op.drop_column('atletaposicao', 'posicao_terciaria_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletaposicao', sa.Column('posicao_terciaria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('atletaposicao', sa.Column('posicao_secundaria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('atletaposicao', sa.Column('posicao_primaria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletaposicao', type_='foreignkey')
    op.create_foreign_key('FK__atletapos__posic__51300E55', 'atletaposicao', 'posicao', ['posicao_secundaria_id'], ['id'])
    op.create_foreign_key('FK__atletapos__posic__5224328E', 'atletaposicao', 'posicao', ['posicao_terciaria_id'], ['id'])
    op.create_foreign_key('FK__atletapos__posic__531856C7', 'atletaposicao', 'posicao', ['posicao_primaria_id'], ['id'])
    op.drop_column('atletaposicao', 'posicao_id')
    # ### end Alembic commands ###
