"""refatorar_tabelas_contrato

Revision ID: c65917c6d83a
Revises: 3eaf33205400
Create Date: 2024-05-16 19:24:59.760773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c65917c6d83a'
down_revision: Union[str, None] = '3eaf33205400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratotipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratosubtipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contrato_tipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_tipo_id'], ['contratotipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_atletacontratoclube_atleta_id', table_name='atletacontratoclube')
    op.drop_index('ix_atletacontratoclube_contrato_id', table_name='atletacontratoclube')
    op.drop_table('atletacontratoclube')
    op.drop_index('ix_atletacontratoempresa_atleta_id', table_name='atletacontratoempresa')
    op.drop_table('atletacontratoempresa')
    op.add_column('contrato', sa.Column('atleta_id', sa.Integer(), nullable=False))
    op.add_column('contrato', sa.Column('contrato_sub_tipo_id', sa.Integer(), nullable=False))
    op.add_column('contrato', sa.Column('data_inicio', sa.Date(), nullable=False))
    op.add_column('contrato', sa.Column('data_termino', sa.Date(), nullable=False))
    op.add_column('contrato', sa.Column('ativo', sa.Boolean(), nullable=False))
    op.add_column('contrato', sa.Column('data_criacao', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'contrato', 'atleta', ['atleta_id'], ['id'])
    op.create_foreign_key(None, 'contrato', 'contratosubtipo', ['contrato_sub_tipo_id'], ['id'])
    op.drop_column('contrato', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato', sa.Column('tipo', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contrato', type_='foreignkey')
    op.drop_constraint(None, 'contrato', type_='foreignkey')
    op.drop_column('contrato', 'data_criacao')
    op.drop_column('contrato', 'ativo')
    op.drop_column('contrato', 'data_termino')
    op.drop_column('contrato', 'data_inicio')
    op.drop_column('contrato', 'contrato_sub_tipo_id')
    op.drop_column('contrato', 'atleta_id')
    op.create_table('atletacontratoempresa',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('data_atualizado', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], name='FK__atletacon__atlet__0C50D423'),
    sa.PrimaryKeyConstraint('id', name='PK__atletaco__3213E83FDB136ABC')
    )
    op.create_index('ix_atletacontratoempresa_atleta_id', 'atletacontratoempresa', ['atleta_id'], unique=False)
    op.create_table('atletacontratoclube',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('data_atualizado', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contrato_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], name='FK__atletacon__atlet__0880433F'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], name='FK__atletacon__contr__09746778'),
    sa.PrimaryKeyConstraint('id', name='PK__atletaco__3213E83F67159CAA')
    )
    op.create_index('ix_atletacontratoclube_contrato_id', 'atletacontratoclube', ['contrato_id'], unique=False)
    op.create_index('ix_atletacontratoclube_atleta_id', 'atletacontratoclube', ['atleta_id'], unique=False)
    op.drop_table('contratosubtipo')
    op.drop_table('contratotipo')
    # ### end Alembic commands ###
