"""adicionar_campo_observacao_tabela_contrato

Revision ID: cf2f5bf0f1c4
Revises: c65917c6d83a
Create Date: 2024-05-16 20:35:40.251674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf2f5bf0f1c4'
down_revision: Union[str, None] = 'c65917c6d83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato', sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contrato', 'observacao')
    # ### end Alembic commands ###
