"""criar_tabela_atleta_videos

Revision ID: d1a90d510109
Revises: 573cc15482f9
Create Date: 2024-06-03 22:40:36.730387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1a90d510109'
down_revision: Union[str, None] = '573cc15482f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atletavideos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sa.Enum('video', 'youtube', name='atletavideotypes'), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizado', sa.DateTime(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atletavideos')
    # ### end Alembic commands ###
