"""adicionar_data_retorno_historico_lesao

Revision ID: d670edc27794
Revises: de0caac9e482
Create Date: 2024-05-23 20:17:49.118824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd670edc27794'
down_revision: Union[str, None] = 'de0caac9e482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicolesao', sa.Column('data_retorno', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historicolesao', 'data_retorno')
    # ### end Alembic commands ###
