"""periodo_vigencia_contrato

Revision ID: db00c5363f7e
Revises: 4ad4aaf631ee
Create Date: 2024-04-23 09:06:55.212075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db00c5363f7e'
down_revision: Union[str, None] = '4ad4aaf631ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletacontrato', sa.Column('data_inicio', sa.Date(), nullable=False))
    op.add_column('atletacontrato', sa.Column('data_fim', sa.Date(), nullable=False))
    op.add_column('atletacontrato', sa.Column('data_criacao', sa.DateTime(), nullable=False))
    op.add_column('atletacontrato', sa.Column('data_atualizado', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atletacontrato', 'data_atualizado')
    op.drop_column('atletacontrato', 'data_criacao')
    op.drop_column('atletacontrato', 'data_fim')
    op.drop_column('atletacontrato', 'data_inicio')
    # ### end Alembic commands ###
