"""adicionar_campo_observacao_tabela_contrato

Revision ID: de0caac9e482
Revises: d880b040be88
Create Date: 2024-05-16 23:45:29.296297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de0caac9e482'
down_revision: Union[str, None] = 'd880b040be88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato', sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contrato', 'observacao')
    # ### end Alembic commands ###
