"""adicionar_constraint_email

Revision ID: ff4de6c59f4e
Revises: 2f8323ed056c
Create Date: 2024-05-06 23:03:20.738185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4de6c59f4e'
down_revision: Union[str, None] = '2f8323ed056c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
